// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _204362LibrarySystem.Models;

namespace _204362LibrarySystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210322111511_make-database-again")]
    partial class makedatabaseagain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
          
        }
    }
}
